export const getEditorConfig = (config = {}) => {
    return {
        language: 'zh-cn',
        toolbar: [
            'heading',
            '|',
            'bold',
            'underline',
            'italic',
            'strikethrough',
            'subscript',
            'superscript',
            '|',
            'bulletedList',
            'numberedList',
            'alignment',
            'outdent',
            'indent',
            '|',
            'fontColor',
            'fontBackgroundColor',
            'fontSize',
            'highlight',
            '|',
            'insertImage',
            'youdeyiwuFileBoxButton',
            'insertTable',
            'mediaEmbed',
            '|',
            'link',
            'horizontalLine',
            'blockQuote',
            'code',
            'codeBlock',
            '|',
            'specialCharacters',
            'findAndReplace',
            'htmlEmbed',
            'showBlocks',
            'pageBreak',
            'removeFormat',
            'undo',
            'redo',
        ]
    }
}